(package "company-makefile"
         "0.0.1"
         "completion backend for gnu makefiles")

(website-url "https://github.com/elp-revive/company-makefile")
(keywords "convenience" "matching")

(package-file "company-makefile.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")

(depends-on "emacs" "26.1")
(depends-on "company")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
